export const servicesData = [
	'Access to dashboard',
	'No. of business listings',
	'No. of products/services',
	'No. of Images',
	'Keywords',
	'Display service hours & prices',
	'Display address, email & contact',
	'Instant chat',
	'Reviews & ratings',
	'Profile visibility',
	'Instant notifications',
	'Display website & social network',
	'Quotes',
	'Bookmarks',
	'Profile views',
	'Verified badge',
	'Latest offers',
	'Accept & sell appointment',
	'24/7  support',
];
