export const servicesData = [
	'Access To Dashboard',
	'Add Up To 10 Businesses',
	'Add Up To 10 Products/Services',
	'Add Up To 6 Images',
	'Unlimited Keywords',
	'Display Service Hours And Prices',
	'Display Address, Contact And Email',
	'Instant Chat',
	'Reviews And Ratings',
	'Landing Page',
	'Profile Visibility',
	'Instant Notifications',
	'Display Social Network',
	'Display Website And Social Network',
	'Quotes',
	'Number Of Profile Views',
	'Verification Badge (gold)',
	'Bookmarks',
	'24/7 Service & Support',
	'Appointments',
	'Latest Offers',
];
